#
# Copyright . All Rights Reserved.
#

version: '3.7'

volumes:
  backend:

services:
  backend:
      container_name: backend.${ORG:-org1}.${DOMAIN:-example.com}
      image: openjdk:jre-alpine
      # volumes: 
      #   - ./backend:/opt/backend #CHANGE ME
      volumes:
      - ${WORK_DIR-/home/docker}/backend:/opt/backend
      environment:
        - API_HOST=api.${ORG:-org1}.${DOMAIN:-example.com}
        - API_PORT=4000
      command: java -jar /opt/backend/factoring.jar
      ports: 
        - 5500:5500
# networks:
#   default:
#     external:
#       name: fabric-overlay