#
# Copyright . All Rights Reserved.
#

version: '3.7'

services:
  cli.clean:
    container_name: cli.clean
#    build:
#      args:
#        FABRIC_VERSION: ${FABRIC_VERSION:-latest}
#      context: ./fabric-tools-extended
    image: olegabu/fabric-tools-extended
    working_dir: /etc/hyperledger
    volumes:
    - /var/run/:/host/var/run/
    - ./crypto-config:/etc/hyperledger/crypto-config

