#
# Copyright . All Rights Reserved.
#

version: '3.7'


services:
  ca:
    ports:
    - ${CA_PORT:-7054}:7054

  peer0:
    ports:
    - ${PEER0_PORT:-7051}:7051
#    - ${PEER0_EVENT_PORT:-7053}:7053

  api:
    volumes: 
      - /Users/vladimirpopov/Blockchain/HLF/fabric-starter-rest:/etc/fabric-starter-rest
    ports:
    - ${API_PORT:-4000}:3000
    - 3100:3100

  www.peer:
    ports:
      - ${WWW_PORT:-80}:80